project:
  type: website
  render:
    - "*.qmd"
    - "!publications/_template/"
    - "!people/_template/"


website:
  title: "Medical AI Lab"
  site-url: "https://baumgach.github.io/mia-website"
  repo-url: "https://github.com/baumgach/mia-website"
  favicon: images/favicon.png
  # google-analytics: "UA-177339812-1"
  # twitter-card: true
  #back-to-top-navigation: true
  page-navigation: false
  search: true
  page-footer: 
    background: "#F6F5F3"
    center: Made with {{< fa brands r-project >}} and 
      [![](https://quarto.org/quarto.png){fig-alt="Quarto" width=65px}](https://quarto.org/) 
    right:
      - icon: github
        href: https://github.com/baumgach/mia-website
  
  navbar:
    search: true
    title: false
    logo: images/logo.png 
    background: "#F6F5F3"
    logo-alt: "Medical AI Group"
    left:
      - href: people/index.qmd
        text: people
      - href: research/index.qmd
      - href: publications/index.qmd
      # - text: "NSF DMREF"
      #   href: dmref/index.qmd
      # - href: codes/index.qmd
      #   text: Codes
      # - href: news/index.qmd
      - href: contact.qmd
        text: Contact

  sidebar:
#  link each group of sidebar entries with a navbar entry by matching their titles and listing the page linked from the navbar as the first content in the sidebar
    - id: dmref
      title: "NSF DMREF"
      # logo: "images/dmref-logo.png"
      logo-href: dmref/index.qmd #avail quarto v 1.5
      contents: 
        - href: dmref/index.qmd
          text: Welcome to DMREF
        - href: dmref/people/index.qmd
          text: The DMREF Team
        - href: dmref/publications/index.qmd
          text: DMREF-Related Publications
        - href: dmref/codes/index.qmd
          text: Computer Codes
        - href: dmref/data/index.qmd
          text: Team Data

    - id: empty-to-suppress-sidebars-on-other-pages


format:
  html:
    theme: 
      - styles/custom.scss
      - yeti
    mainfont: Nunito Sans
    toc: true
    link-external-newwindow: true
    date-format: "MMM YYYY"
    smooth-scroll: true
    resources:
      - images



